### ISSUE TITLE
HPRC Release 2: genotyping-pipelines.prepare-vcf-MC

### ISSUE THREAD

**Issue by kmertide** [eblerjana/genotyping-pipelines#4]
Hi Jana,

Thank you for your clear documentation and support in getting PanGenie up and running. Could you please confirm whether the following steps are correct for preparing input files for genotyping-pipelines.prepare-vcf-MC using the HPRC release 2?

1. Pull release 2 input files
```bash

aws s3 cp s3://human-pangenomics/pangenomes/scratch/2025_02_28_minigraph_cactus/hprc-v2.0-mc-chm13/hprc-v2.0-mc-chm13.vcf.gz .

aws s3 cp s3://human-pangenomics/pangenomes/scratch/2025_02_28_minigraph_cactus/hprc-v2.0-mc-chm13/hprc-v2.0-mc-chm13.full.gfa.gz .
```

2. Run [vcfbub](https://github.com/pangenome/vcfbub) to remove non-top level bubbles
```bash
./vcfbub -l 0 -a 100000 -i hprc-v2.0-mc-chm13.vcf.gz > hprc-v2.0-mc-chm13.vcf.vcfbub.gz
```

or should I run this vcfbub (considering the git issue: https://github.com/eblerjana/genotyping-pipelines/issues/2)

```bash
vcfbub -l 0 -r 100000 --input hprc-v2.0-mc-chm13.vcf.gz | bgzip > mc.vcf.gz && tabix -p vcf mc.vcf.gz
```

And then use the resulting VCF (mc.vcf.gz) as input to prepare-vcf-MC?

3. Remove GRCh38 genotypes (due to diploid)

```bash
zcat  hprc-v2.0-mc-chm13.vcf.vcfbub.gz \
| cut --complement -d$'\t' -f10 \
| bgzip -@128 >  hprc-v2.0-mc-chm13.vcf.vcfbub.no-grch38.vcf.gz
```

4. Setup configuration for genotyping-pipelines.prepare-vcf-MC 

```yaml
# name of the folder to write the results to
results: "results"

# callsets generated by Minigraph-Cactus pipeline (already filtered with vcfbub)
callsets:
 hprc-v2.0-mc-chm13:
  # Minigraph-Cactus VCF after vcfbub -l 0 -r 100000 --input <your-vcf-file> > pangenie-ready.vcf
  vcf: "hprc-v2.0-mc-chm13.vcf.vcfbub.no-grch38.vcf.gz"
  # Minigraph-Cactus graph GFA
  gfa: "hprc-v2.0-mc-chm13.full.gfa.gz"
  # TSV file specifying sex (1=male, 2=female) of each sample in input VCF. Format: <sample-name> <sex>. 
  sample_info: "sample-info.tsv" 
  # prefix used for chromosome names in FASTA file. 
  reference_prefix: "chr"
  # Choose between: CHM13 | GRCh38
  reference_version: "CHM13"

```
Note: sample-info.tsv was created from [hprc_release2_sample_metadata.csv](https://github.com/human-pangenomics/hprc_intermediate_assembly/blob/main/data_tables/sample/hprc_release2_sample_metadata.csv)

Please let me know if this setup looks good or if any adjustments are needed.

Best,
Andrew
